// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SOAT-46/fastfood-operations/internal/orders"
	"github.com/SOAT-46/fastfood-operations/internal/orders/adapters/http/controllers"
	"github.com/SOAT-46/fastfood-operations/internal/shared"
)

// Injectors from wire.go:

func injectApps() []shared.App {
	createOrderController := controllers.NewCreateOrderController()
	app := orders.NewApp(createOrderController)
	v := newApps(app)
	return v
}

// wire.go:

func newApps(orders2 *orders.App,
) []shared.App {

	return []shared.App{orders2}
}
