services:
  fastfood_operations_server:
    container_name: api
    build:
      context: ../
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - application-network
    depends_on:
      - fastfood_database
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
  fastfood_database:
    container_name: fastfood_database
    image: mongodb/mongodb-community-server:7.0.14-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=fastfood_operations_database
    restart: always
    ports:
      - "${DB_PORT:-27017}:27017"
    volumes:
      - db-data:/data/db
    networks:
      - application-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '2GB'
volumes:
  db-data:

networks:
  application-network:
    driver: bridge
