name: Golang Workflow

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  checks: 'write' # code_check-style_golangci_lint
  contents: 'write' # delivery-release

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache: false

      - name: Run lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          config: .golangci.yaml

      - name: Install dependencies
        run: |
          cd cmd
          go get .

      - name: Build
        run: go build -v ./...

      - name: Ensure test script is executable
        run: chmod +x .github/scripts/run_tests.sh

      - name: Run tests
        run: .github/scripts/run_tests.sh
