name: Golang Workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.go'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          config: fastfood-operations/.golangci.yaml
